<?php

/**
 * PluginmyQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmyQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmyQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmyQuestion');
    }
}