generator:
  class: sfDoctrineGenerator
  param:
    model_class:           myQuestion
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          myQuestionAdmin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:         { label: Отправитель }
        email:        { label: E-Mail }
        subj:         { label: Тема }
        city:         { label: Город }
        link_to_show: { label: Тема }
        created_at:   { label: Отправлено }
        cc_id:        { label: Копия партнеру }
      list:
        title:      Вопросы пользователей <a href="#" onclick="jQuery('#sf_admin_bar').slideToggle('slow')">(поиск)</a>
        display:    [subj, name, email, city, created_at]
        sort:       [created_at, DESC]
        batch_actions: {}
        actions: {}
        object_actions:
          "Просмотр":
            action: show
      filter:
        display:    [email, city, subj, created_at]
      form:    ~
      edit:    ~
      new:     ~
